import { test, expect, type Page } from '@playwright/test';
async function add(page: Page, company: string) {
  await page.getByRole('button',{name:'New opportunity',exact:true}).click();
  await page.getByLabel('Company',{exact:false}).first().fill(company);
  await page.getByRole('button',{name:'Add opportunity',exact:true}).last().click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('button',{name:`Open ${company}`,exact:true})).toBeVisible();
}
test('create, edit, search, list stage change, reload, close, remove, undo, and export', async ({page,request}) => {
  const errors: string[] = []; page.on('pageerror',error => errors.push(error.message));
  await page.goto('/'); await expect(page.getByText('Saved locally')).toBeVisible();
  await add(page,'QA Cedar');
  await page.getByRole('button',{name:'Open QA Cedar',exact:true}).click();
  await page.getByLabel('Role',{exact:true}).fill('Example Role');
  await page.getByLabel('Location / work setup').fill('User-defined location');
  await page.getByLabel('Notes',{exact:true}).fill('Interview notes\nAsk about product ownership');
  await page.getByLabel('Next step',{exact:true}).fill('Send portfolio');
  await page.getByLabel('Follow-up date').fill('2026-01-01');
  await page.getByLabel('Priority',{exact:true}).selectOption('high');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload(); await expect(page.getByText('Example Role',{exact:true})).toBeVisible();
  await page.getByLabel('Search opportunities').fill('nothing-matches');
  await expect(page.getByRole('button',{name:'Open QA Cedar',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Clear filters',exact:false}).click();
  await page.getByRole('tab',{name:'List',exact:true}).click();
  await page.getByLabel('Stage for QA Cedar').selectOption('interested');
  await expect(page.getByText('QA Cedar moved to Interested')).toBeVisible();
  await page.reload(); await expect(page.getByLabel('Stage for QA Cedar')).toHaveValue('interested');
  await page.getByLabel('Stage for QA Cedar').selectOption('interview');
  await expect(page.getByLabel('Stage for QA Cedar')).toHaveValue('interview');
  await expect(page.getByText('QA Cedar moved to Interview')).toBeVisible();
  await page.reload(); await expect(page.getByLabel('Stage for QA Cedar')).toHaveValue('interview');
  await page.getByRole('button',{name:'Open QA Cedar',exact:true}).click();
  await expect(page.getByLabel('Notes',{exact:true})).toHaveValue('Interview notes\nAsk about product ownership');
  await page.getByLabel('Stage',{exact:true}).selectOption('accepted');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.getByLabel('Stage for QA Cedar')).toHaveValue('accepted');
  await page.getByRole('button',{name:'Open QA Cedar',exact:true}).click();
  await page.getByRole('button',{name:'Remove opportunity',exact:true}).click();
  await page.getByRole('alertdialog').getByRole('button',{name:'Remove opportunity',exact:true}).click();
  await expect(page.getByRole('button',{name:'Open QA Cedar',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await expect(page.getByRole('button',{name:'Open QA Cedar',exact:true})).toBeVisible();
  const backup = await request.get('/api/export'); expect(backup.ok()).toBeTruthy(); expect((await backup.json()).opportunities.some((job: {company:string}) => job.company==='QA Cedar')).toBeTruthy();
  expect(errors).toEqual([]);
});
test('pointer drag changes stage and ordering, persisted after refresh', async ({page,request}) => {
  await page.goto('/'); await page.getByRole('tab',{name:'Board',exact:true}).click();
  await add(page,'QA Alder'); await add(page,'QA Birch');
  const source = page.getByRole('button',{name:'Open QA Birch',exact:true});
  const target = page.getByRole('button',{name:'Open QA Alder',exact:true});
  const a = await source.boundingBox(); const b = await target.boundingBox();
  if (!a || !b) throw new Error('Cards not visible');
  await page.mouse.move(a.x+55,a.y+35); await page.mouse.down(); await page.mouse.move(a.x+55,a.y+25,{steps:3}); await page.mouse.move(b.x+55,b.y+15,{steps:15}); await page.mouse.up();
  await expect.poll(async () => (await (await request.get('/api/opportunities')).json()).opportunities.filter((job:{stage:string})=>job.stage==='prospect').map((job:{company:string})=>job.company)).toEqual(['QA Birch','QA Alder']);
  await expect(page.getByText('Order saved',{exact:true})).toBeVisible();
  await expect(source.locator('..')).toHaveCSS('transform','none');
  const source2 = await source.boundingBox(); const lane = await page.locator('[data-stage="interested"]').boundingBox(); if (!source2 || !lane) throw new Error('Drop target not visible');
  await page.mouse.move(source2.x+65,source2.y+35); await page.mouse.down(); await page.mouse.move(source2.x+75,source2.y+35,{steps:3}); await page.mouse.move(lane.x+80,lane.y+100,{steps:20}); await page.mouse.up();
  await expect(page.locator('[data-stage="interested"]').getByRole('button',{name:'Open QA Birch',exact:true})).toBeVisible();
  await page.reload(); await expect(page.locator('[data-stage="interested"]').getByRole('button',{name:'Open QA Birch',exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/desktop-board.png',fullPage:true});
});
test('mobile editor, unsaved-change protection, keyboard move, and database error handling', async ({page,request}) => {
  await page.setViewportSize({width:390,height:844}); await page.goto('/');
  await expect(page.getByRole('button',{name:'New opportunity',exact:true})).toBeVisible();
  await add(page,'QA Mobile');
  await page.getByRole('button',{name:'Open QA Mobile',exact:true}).click();
  await page.getByLabel('Role',{exact:true}).fill('Unsaved');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(page.getByRole('alertdialog')).toBeVisible();
  await page.getByRole('button',{name:'Discard changes',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.screenshot({path:'test-results/mobile-board.png',fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.setViewportSize({width:1512,height:982});
  // Start keyboard verification from a fresh page, after the modal focus-restoration lifecycle.
  await page.reload();
  const handle = page.getByRole('button',{name:'Move QA Mobile',exact:true});
  await handle.press('Space');
  await expect(handle).toHaveAttribute('aria-pressed','true');
  const liveRegion = page.locator('[id^="DndLiveRegion"]');
  const beforeDrop = (await (await request.get('/api/opportunities')).json()).opportunities;
  const currentCard = beforeDrop.find((job:{company:string})=>job.company==='QA Mobile');
  await expect(liveRegion).toContainText(`over droppable area ${currentCard.id}`);
  await page.keyboard.press('ArrowRight');
  const nextCard = beforeDrop.filter((job:{stage:string})=>job.stage==='interested')[0];
  await expect(liveRegion).toContainText(`over droppable area ${nextCard?.id || 'interested'}`);
  await page.keyboard.press('Space');
  await expect.poll(async () => (await (await request.get('/api/opportunities')).json()).opportunities.find((job:{company:string})=>job.company==='QA Mobile').stage).toBe('interested');
  await page.getByRole('button',{name:'Open QA Mobile',exact:true}).click();
  await page.getByLabel('Role',{exact:true}).fill('Keep this draft');
  await page.route('**/api/opportunities/*',route => route.request().method()==='PATCH' ? route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Simulated save failure'})}) : route.continue());
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.getByRole('alert')).toHaveText('Simulated save failure');
  await expect(page.getByLabel('Role',{exact:true})).toHaveValue('Keep this draft');
  await page.unrouteAll();
});
test('API rejects cross-origin writes and stale versions',async ({request}) => {
  expect((await request.patch('/api/profile',{headers:{Origin:'https://untrusted.example'},data:{version:0,roles:'Unwanted change'}})).status()).toBe(403);
  const denied = await request.post('/api/opportunities',{headers:{Origin:'https://untrusted.example'},data:{company:'Should not exist'}}); expect(denied.status()).toBe(403);
  const invalid = await request.post('/api/opportunities',{data:{company:'Unsafe link',url:'javascript:alert(1)'}}); expect(invalid.status()).toBe(400);
  const create = await request.post('/api/opportunities',{data:{company:'Version test'}}); const {opportunity:job} = await create.json();
  expect((await request.patch(`/api/opportunities/${job.id}`,{data:{version:job.version,notes:'First edit'}})).ok()).toBeTruthy();
  expect((await request.patch(`/api/opportunities/${job.id}`,{data:{version:job.version,notes:'Stale edit'}})).status()).toBe(409);
});

test('search preferences start undecided and persist in the app, API and export', async ({page,request}) => {
  await page.goto('/');
  await expect(page.getByText('What are you looking for?',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Set up your search',exact:false}).click();
  await expect(page.getByLabel('Roles and work you want',{exact:true})).toHaveValue('');
  await expect(page.getByLabel('Work arrangement',{exact:true})).toHaveValue('');
  await page.getByLabel('Roles and work you want',{exact:true}).fill('Museum education and public programmes');
  await page.getByLabel('Location and work eligibility',{exact:true}).fill('My selected region and eligibility');
  await page.getByLabel('Employment type and hours',{exact:true}).fill('Part-time employee');
  await page.getByLabel('Things to avoid',{exact:true}).fill('Sales targets');
  await page.getByRole('button',{name:'Save preferences',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByText('Search preferences saved',{exact:true})).toBeVisible();
  await expect(page.getByText('What are you looking for?',{exact:true})).toHaveCount(0);
  await page.reload();
  await page.getByRole('button',{name:'Search preferences',exact:true}).click();
  await expect(page.getByLabel('Roles and work you want',{exact:true})).toHaveValue('Museum education and public programmes');
  const {profile} = await (await request.get('/api/profile')).json();
  expect(profile.roles).toBe('Museum education and public programmes');
  expect(profile.employmentType).toBe('Part-time employee');
  expect(profile.version).toBe(1);
  const exported = await (await request.get('/api/export')).json();
  expect(exported.profile).toEqual(profile);
  expect(exported.version).toBe(3);
  await page.screenshot({path:'test-results/search-preferences-desktop.png',fullPage:true});
});

test('agent setup saves a handoff without claiming a schedule was created',async ({page,request}) => {
  await page.goto('/'); await page.getByRole('button',{name:'Search agent',exact:true}).click();
  await page.getByLabel('Choose your desktop agent').selectOption('claude-code');
  await page.getByLabel('When should it search?').fill('Mondays at 10:00');
  await page.getByLabel('Timezone',{exact:true}).fill('Europe/Prague');
  await page.getByRole('button',{name:'Save setup choices'}).click();
  await expect(page.getByText('Setup choices saved.',{exact:false})).toBeVisible();
  await expect(page.getByText('No scheduled task has been reported yet.')).toBeVisible();
  const state = await (await request.get('/api/agent')).json();
  expect(state.schedule.taskId).toBe(''); expect(state.schedule.reportedAt).toBeNull();
  expect(state.schedule.provider).toBe('claude-code');
  const setup = await (await request.get('/api/agent/setup')).json();
  expect(setup.instructions).toContain('Mondays at 10:00'); expect(setup.instructions).toContain('Claude Code Desktop');
  expect(setup.instructions).toContain('Never edit app code');
  await page.reload(); await page.getByRole('button',{name:'Search agent',exact:true}).click();
  await expect(page.getByLabel('When should it search?')).toHaveValue('Mondays at 10:00');
  await page.getByLabel('When should it search?').fill('An unsaved schedule');
  await page.getByRole('button',{name:'Close',exact:true}).first().click();
  await expect(page.getByRole('alertdialog')).toBeVisible();
  await page.getByRole('button',{name:'Discard changes',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
});

test('mobile agent setup preserves drafts when saving fails',async ({page}) => {
  await page.setViewportSize({width:390,height:844}); await page.goto('/');
  await page.getByRole('button',{name:'Search agent',exact:true}).click();
  await page.getByLabel('When should it search?').fill('Keep this schedule draft');
  await page.route('**/api/agent/schedule',route => route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Simulated setup failure'})}));
  await page.getByRole('button',{name:'Save setup choices'}).click();
  await expect(page.getByRole('alert')).toHaveText('Simulated setup failure');
  await expect(page.getByLabel('When should it search?')).toHaveValue('Keep this schedule draft');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({path:'test-results/mobile-agent.png',fullPage:true});
});

test('search preferences preserve drafts on conflicts and failed saves', async ({page,request}) => {
  await page.goto('/');
  await page.getByRole('button',{name:'Search preferences',exact:true}).click();
  const roles = page.getByLabel('Roles and work you want',{exact:true});
  await roles.fill('My unsaved role preferences');
  const {profile} = await (await request.get('/api/profile')).json();
  const update = await request.patch('/api/profile',{data:{version:profile.version,roles:'A change from the setup agent'}});
  expect(update.ok()).toBeTruthy();
  await page.getByRole('button',{name:'Save preferences',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Search preferences changed elsewhere');
  await expect(roles).toHaveValue('My unsaved role preferences');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Discard changes',exact:true}).click();
  await page.getByRole('button',{name:'Search preferences',exact:true}).click();
  await expect(roles).toHaveValue('A change from the setup agent');
  await roles.fill('Keep this profile draft');
  await page.route('**/api/profile',route => route.request().method()==='PATCH' ? route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Simulated preference save failure'})}) : route.continue());
  await page.getByRole('button',{name:'Save preferences',exact:true}).click();
  await expect(page.getByRole('alert')).toHaveText('Simulated preference save failure');
  await expect(roles).toHaveValue('Keep this profile draft');
  await page.unrouteAll();
});

test('mobile preferences can be edited, discarded and deliberately left undecided', async ({page}) => {
  await page.setViewportSize({width:390,height:844}); await page.goto('/');
  await page.getByRole('button',{name:'Search preferences',exact:true}).click();
  const roles = page.getByLabel('Roles and work you want',{exact:true});
  await roles.fill('An unsaved change');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Keep editing',exact:true}).click();
  await expect(page.getByRole('alertdialog')).toHaveCount(0);
  await expect(roles).toHaveValue('An unsaved change');
  await page.screenshot({path:'test-results/search-preferences-mobile.png',fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await roles.fill('');
  await page.getByRole('button',{name:'Save preferences',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await expect(page.getByText('What are you looking for?',{exact:true})).toBeVisible();
});
test('conflicting edits preserve the draft and reopening loads the other window’s version', async ({page,request}) => {
  await page.goto('/'); await add(page,'QA Conflict');
  await page.getByRole('button',{name:'Open QA Conflict',exact:true}).click();
  await page.getByLabel('Role',{exact:true}).fill('My draft');
  const job = (await (await request.get('/api/opportunities')).json()).opportunities.find((job:{company:string})=>job.company==='QA Conflict');
  await request.patch(`/api/opportunities/${job.id}`,{data:{version:job.version,role:'Other window’s update'}});
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('changed in another window');
  await expect(page.getByLabel('Role',{exact:true})).toHaveValue('My draft');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Discard changes',exact:true}).click();
  await page.getByRole('button',{name:'Open QA Conflict',exact:true}).click();
  await expect(page.getByLabel('Role',{exact:true})).toHaveValue('Other window’s update');
});
test('Uninterested moves persist and hiding the column preserves list access and the visibility preference', async ({page,request}) => {
  await page.goto('/');
  await expect(page.locator('.board-column').first()).toHaveAttribute('aria-label','Uninterested stage');
  await add(page,'QA Not a fit');
  const card = page.getByRole('button',{name:'Open QA Not a fit',exact:true});
  const source = await card.boundingBox();
  const target = await page.locator('[data-stage="uninterested"]').boundingBox();
  if (!source || !target) throw new Error('Uninterested drop target not visible');
  await page.mouse.move(source.x+55,source.y+35); await page.mouse.down();
  await page.mouse.move(source.x+45,source.y+35,{steps:3});
  await page.mouse.move(target.x+70,target.y+80,{steps:20}); await page.mouse.up();
  await expect(page.getByText('QA Not a fit moved to Uninterested')).toBeVisible();
  await expect(page.getByRole('region',{name:'Uninterested stage',exact:true}).getByRole('button',{name:'Open QA Not a fit',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Hide uninterested',exact:true}).click();
  await expect(page.getByRole('region',{name:'Uninterested stage',exact:true})).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('button',{name:'Show uninterested',exact:true})).toBeVisible();
  await expect(page.locator('.board-column').first()).toHaveAttribute('aria-label','Prospects stage');
  await expect(card).toHaveCount(0);
  const saved = (await (await request.get('/api/opportunities')).json()).opportunities.find((job:{company:string}) => job.company==='QA Not a fit');
  expect(saved.stage).toBe('uninterested');
  await page.getByRole('tab',{name:'List',exact:true}).click();
  await expect(page.getByLabel('Stage for QA Not a fit')).toHaveValue('uninterested');
  await page.getByLabel('Stage for QA Not a fit').selectOption('prospect');
  await expect(page.getByText('QA Not a fit moved to Prospects')).toBeVisible();
  await page.getByLabel('Stage for QA Not a fit').selectOption('uninterested');
  await expect(page.getByText('QA Not a fit moved to Uninterested')).toBeVisible();
  await page.getByRole('tab',{name:'Board',exact:true}).click();
  await page.getByRole('button',{name:'Show uninterested',exact:true}).click();
  await page.reload();
  await expect(page.getByRole('region',{name:'Uninterested stage',exact:true}).getByRole('button',{name:'Open QA Not a fit',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Hide uninterested',exact:true})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Hide uninterested',exact:true}).click();
  await expect(page.getByRole('button',{name:'Show uninterested',exact:true})).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});
