import { ArrowDownAZ, CalendarDays, Plus, Star } from 'lucide-react';
import { Table, TableHeader, TableBody, TableHead, TableRow, TableCell } from '@/components/ui/table';
import { Empty, EmptyDescription, EmptyTitle } from '@/components/ui/empty';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { STAGES, dateLabel, today, type Opportunity, type StageId } from '@/lib/model';
import { CompanyMark } from './job-board';
export default function JobList({ jobs, onOpen, onMove, onAdd, busy, filtered }: { jobs: Opportunity[]; onOpen: (job: Opportunity) => void; onMove: (job: Opportunity, stage: StageId, before: string|null) => void; onAdd: () => void; busy: boolean; filtered: boolean }) {
  return <div className="list-surface"><Table><TableHeader><TableRow><TableHead>Company & role</TableHead><TableHead>Stage</TableHead><TableHead>Location</TableHead><TableHead>Next step</TableHead><TableHead>Follow-up</TableHead><TableHead>Priority</TableHead></TableRow></TableHeader><TableBody>{jobs.map(job => <TableRow key={job.id}><TableCell><button className="list-company" onClick={() => onOpen(job)} aria-label={`Open ${job.company}`}><CompanyMark company={job.company}/><span><strong>{job.company}</strong><span>{job.role || 'Role to explore'}</span></span></button></TableCell><TableCell><NativeSelect className="list-stage" value={job.stage} aria-label={`Stage for ${job.company}`} onChange={e => onMove(job, e.target.value as StageId, null)} disabled={busy}>{STAGES.map(stage => <NativeSelectOption value={stage.id} key={stage.id}>{stage.name}</NativeSelectOption>)}</NativeSelect></TableCell><TableCell className="muted-cell">{job.location || '—'}</TableCell><TableCell><div className="list-next-step">{job.nextStep || <span className="muted-cell">—</span>}</div></TableCell><TableCell>{job.followUp ? <span className={`due-date ${job.followUp < today() ? 'overdue' : job.followUp === today() ? 'due-today' : ''}`}><CalendarDays size={13}/>{dateLabel(job.followUp)}{job.followUp < today() ? ' · overdue' : ''}</span> : <span className="muted-cell">—</span>}</TableCell><TableCell><span className={`priority-badge priority-${job.priority}`}>{job.priority === 'high' && <Star size={12}/>}{{high:'High',normal:'Normal',low:'Low'}[job.priority]}</span></TableCell></TableRow>)}</TableBody></Table>{jobs.length === 0 && <Empty className="list-empty"><ArrowDownAZ size={28}/><EmptyTitle>{filtered ? 'No matching opportunities' : 'Your next opportunity starts here'}</EmptyTitle><EmptyDescription>{filtered ? 'Try another search or clear your filters.' : 'Add a company you’d like to work with.'}</EmptyDescription>{!filtered && <button className="primary-button" onClick={onAdd}><Plus size={16}/>Add your first opportunity</button>}</Empty>}</div>;
}
